swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  # New: Create a User Account
  /users:
    post:
      tags:
        - Users
      summary: Create a New User Account
      description: API to create a new user account
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      produces:
        - application/json
      responses:
        '201':
          description: User account created successfully
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid data provided

  # New: Get a User's Bank Accounts
  /accounts/{userId}:
    get:
      tags:
        - Accounts
      summary: Get a User's Bank Accounts
      description: API to obtain a user's bank accounts
      parameters:
        - in: path
          name: userId
          required: true
          type: string
          description: Unique ID of the user
      produces:
        - application/json
      responses:
        '200':
          description: List of bank accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '404':
          description: User not found
   
    # New: Account Update
    put:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: Update User Account
      description: API for updating a user's account
      parameters:
        - in: path
          name: userId
          type: string
          required: true
          description: Unique ID of the user
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: User account updated successfully
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: User not found

  # New: Delete Account
  /user/{userId}:
    delete:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: Delete User Account
      description: API for deleting a user's account
      parameters:
        - in: path
          name: userId
          type: string
          required: true
          description: Unique ID of the user
      produces:
        - application/json
      responses:
        '200':
          description: User account deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found

 # New: Create a Transaction
  /transactions:
    post:
      tags:
        - Transactions
      summary: Create a New Transaction
      description: Allows a user to create a financial transaction on their account.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewTransaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction created successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid transaction data

  # New: Get Transactions for a Specific Account
  /transactions/{accountId}:
    get:
      tags:
        - Transactions
      summary: Get Transactions for a Specific Account
      description: Retrieves a list of transactions for a specific account
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '404':
          description: Account not found


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
        
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
            
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  NewUser:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
    required:
      - firstName
      - lastName
      - email
      - password

  Account:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      type:
        type: string
        enum: [checking, savings, credit]
      balance:
        type: number
    required:
      - id
      - userId
      - type
      - balance
  
  UserUpdate:
    type: object
    properties:
      email:
        type: string
        description: Updated email of the user
      password:
        type: string
        description: Updated password of the user
      firstName:
        type: string
        description: Updated first name of the user
      lastName:
        type: string
        description: Updated last name of the user
    required:
      - email
      - firstName
      - lastName

  UserOperationResponse:
    type: object
    properties:
      status:
        type: integer
        description: Status code of the operation
      message:
        type: string
        description: Message describing the result of the operation
      data:
        type: object
        properties:
          userId:
            type: string
            description: ID of the user who was updated or deleted

  NewTransaction:
    type: object
    properties:
      accountId:
        type: string
        description: The unique identifier of the account on which the transaction is performed.
      type:
        type: string
        enum: [deposit, debit, payment, transfer]
        description: Type of transaction (deposit, withdrawal, payment, transfer).
      amount:
        type: number
        description: Amount of the transaction.
      date:
        type: string
        format: date-time
        description: Date and time when the transaction was performed.
    required:
      - accountId
      - type
      - amount
      - date

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier of the transaction.
      accountId:
        type: string
        description: Unique identifier of the account associated with the transaction.
      type:
        type: string
        enum: [deposit, debit, payment, transfer]
        description: Type of transaction performed.
      amount:
        type: number
        description: Amount of the transaction.
      date:
        type: string
        format: date-time
        description: Date and time of the transaction.